namespace Dhole.DataExtraction.Infrastructure.Mapping;

public static class DefaultFclColumnMappings
{
    public static readonly IReadOnlyDictionary<string, string> Mappings = new Dictionary<string, string>
    {
        ["actualizado"] = "UpdatedAt",
        ["updatedat"] = "UpdatedAt",
        ["updated"] = "UpdatedAt",
        ["lastupdate"] = "UpdatedAt",
        ["lastupdated"] = "UpdatedAt",

        ["pol"] = "OriginPort",
        ["origin"] = "OriginPort",
        ["origen"] = "OriginPort",
        ["originport"] = "OriginPort",
        ["puertoorigen"] = "OriginPort",
        ["portloading"] = "OriginPort",
        ["portofloading"] = "OriginPort",
        ["loading"] = "OriginPort",
        ["loadingport"] = "OriginPort",
        ["loadport"] = "OriginPort",
        ["from"] = "OriginPort",
        ["por"] = "OriginPort",
        ["placeofreceipt"] = "OriginPort",
        ["receipt"] = "OriginPort",

        ["poe"] = "PortOfExit",
        ["portofexit"] = "PortOfExit",
        ["exitport"] = "PortOfExit",
        ["puertosalida"] = "PortOfExit",
        ["transshipmentport"] = "PortOfExit",
        ["transshipment"] = "PortOfExit",
        ["transbordo"] = "PortOfExit",
        ["via"] = "PortOfExit",

        ["pod"] = "DestinationPort",
        ["destination"] = "DestinationPort",
        ["destino"] = "DestinationPort",
        ["destinationport"] = "DestinationPort",
        ["puertodestino"] = "DestinationPort",
        ["portdischarge"] = "DestinationPort",
        ["portofdischarge"] = "DestinationPort",
        ["discharge"] = "DestinationPort",
        ["dischargeport"] = "DestinationPort",
        ["finaldestination"] = "DestinationPort",
        ["placeofdelivery"] = "DestinationPort",
        ["delivery"] = "DestinationPort",
        ["to"] = "DestinationPort",

        ["carrier"] = "Carrier",
        ["naviera"] = "Carrier",
        ["linea"] = "Carrier",
        ["lineamaritima"] = "Carrier",
        ["shippingline"] = "Carrier",
        ["steamshipline"] = "Carrier",
        ["shippingcompany"] = "Carrier",
        ["ssl"] = "Carrier",
        ["oceanline"] = "Carrier",
        ["line"] = "Carrier",

        ["agent"] = "Agent",
        ["agente"] = "Agent",
        ["forwarder"] = "Agent",
        ["proveedor"] = "Agent",
        ["provider"] = "Agent",

        ["container"] = "ContainerType",
        ["containersize"] = "ContainerType",
        ["containersizetype"] = "ContainerType",
        ["containertype"] = "ContainerType",
        ["containercode"] = "ContainerType",
        ["equipment"] = "ContainerType",
        ["equipmentsize"] = "ContainerType",
        ["equipmenttype"] = "ContainerType",
        ["equipmentcode"] = "ContainerType",
        ["equipo"] = "ContainerType",
        ["tipocontenedor"] = "ContainerType",
        ["contenedor"] = "ContainerType",
        ["cntr"] = "ContainerType",
        ["eq"] = "ContainerType",
        ["equip"] = "ContainerType",
        ["eqtype"] = "ContainerType",
        ["type"] = "ContainerType",
        ["size"] = "ContainerType",
        ["sizetype"] = "ContainerType",

        ["commodity"] = "Commodity",
        ["mercancia"] = "Commodity",
        ["producto"] = "Commodity",
        ["cargo"] = "Commodity",
        ["cargotype"] = "Commodity",
        ["descripcion"] = "Commodity",
        ["description"] = "Commodity",

        ["currency"] = "Currency",
        ["moneda"] = "Currency",
        ["curr"] = "Currency",
        ["ccy"] = "Currency",
        ["divisa"] = "Currency",

        ["diastransito"] = "TransitDays",
        ["transitdays"] = "TransitDays",
        ["transittimedays"] = "TransitDays",
        ["transitdayscount"] = "TransitDays",
        ["diastransitocantidad"] = "TransitDays",
        ["tiempotransito"] = "TransitDays",
        ["tiempoentransito"] = "TransitDays",
        ["transittime"] = "TransitDays",
        ["tt"] = "TransitDays",

        ["diaslibres"] = "FreeDays",
        ["freedays"] = "FreeDays",
        ["freetime"] = "FreeDays",
        ["free"] = "FreeDays",
        ["fd"] = "FreeDays",
        ["demurragefreedays"] = "FreeDays",
        ["detentionfreedays"] = "FreeDays",
        ["demdetfreedays"] = "FreeDays",

        ["validfrom"] = "ValidFrom",
        ["vigencia"] = "ValidFrom",
        ["vigenciadesde"] = "ValidFrom",
        ["inicio"] = "ValidFrom",
        ["fechainicio"] = "ValidFrom",
        ["start"] = "ValidFrom",
        ["startdate"] = "ValidFrom",
        ["desde"] = "ValidFrom",
        ["effective"] = "ValidFrom",
        ["effectivedate"] = "ValidFrom",
        ["effectivefrom"] = "ValidFrom",
        ["validityfrom"] = "ValidFrom",

        ["validto"] = "ValidTo",
        ["validuntil"] = "ValidTo",
        ["vigenciahasta"] = "ValidTo",
        ["vence"] = "ValidTo",
        ["vencimiento"] = "ValidTo",
        ["fechavencimiento"] = "ValidTo",
        ["fin"] = "ValidTo",
        ["fechafin"] = "ValidTo",
        ["hasta"] = "ValidTo",
        ["validity"] = "ValidTo",
        ["validityto"] = "ValidTo",
        ["expiration"] = "ValidTo",
        ["expirationdate"] = "ValidTo",
        ["expiracion"] = "ValidTo",
        ["expiry"] = "ValidTo",
        ["expiredate"] = "ValidTo",
        ["effectiveto"] = "ValidTo",

        ["oceanfreight"] = "OceanFreight",
        ["freight"] = "OceanFreight",
        ["freightamount"] = "OceanFreight",
        ["freightcost"] = "OceanFreight",
        ["oceanfreightamount"] = "OceanFreight",
        ["seafreight"] = "OceanFreight",
        ["basicfreight"] = "OceanFreight",
        ["freightrate"] = "OceanFreight",
        ["rate"] = "OceanFreight",
        ["rateamount"] = "OceanFreight",
        ["rateusd"] = "OceanFreight",
        ["amount"] = "OceanFreight",
        ["tarifa"] = "OceanFreight",
        ["precio"] = "OceanFreight",
        ["price"] = "OceanFreight",
        ["flete"] = "OceanFreight",
        ["fleteamount"] = "OceanFreight",
        ["montoflete"] = "OceanFreight",
        ["montotarifa"] = "OceanFreight",
        ["fleteoceanico"] = "OceanFreight",
        ["fletemaritimocosto"] = "OceanFreight",
        ["fleteoceanicocosto"] = "OceanFreight",
        ["of"] = "OceanFreight",
        ["ocf"] = "OceanFreight",

        ["fixedcosts"] = "Surcharges",
        ["fixedcost"] = "Surcharges",
        ["costosfijos"] = "Surcharges",
        ["costofijo"] = "Surcharges",
        ["charges"] = "Surcharges",
        ["localcharges"] = "Surcharges",
        ["surcharges"] = "Surcharges",
        ["recargos"] = "Surcharges",
        ["extras"] = "Surcharges",

        ["profitagentecosto"] = "AgentProfitCost",
        ["agentprofitcost"] = "AgentProfitCost",
        ["releaseagentecosto"] = "AgentReleaseCost",
        ["agentreleasecost"] = "AgentReleaseCost",
        ["releasecosto"] = "AgentReleaseCost",
        ["thcdcosto"] = "DestinationThcCost",
        ["thddcosto"] = "DestinationThcCost",
        ["thcd"] = "DestinationThcCost",
        ["thcdestinationcosto"] = "DestinationThcCost",
        ["documentacioncosto"] = "DocumentationCost",
        ["documentationcost"] = "DocumentationCost",
        ["containerprotectcosto"] = "ContainerProtectCost",
        ["containerprotectioncosto"] = "ContainerProtectCost",
        ["muellajecosto"] = "WharfageCost",
        ["wharfagecost"] = "WharfageCost",
        ["merchantcosto"] = "MerchantCost",
        ["merchantcost"] = "MerchantCost",
        ["fleteinternocosto"] = "InternalFreightCost",
        ["internalfreightcost"] = "InternalFreightCost",
        ["carruselcosto"] = "CarouselCost",
        ["carouselcost"] = "CarouselCost",
        ["manejosptycosto"] = "PanamaHandlingCost",
        ["manejospty"] = "PanamaHandlingCost",
        ["panamahandlingcost"] = "PanamaHandlingCost",
        ["fleteinternacionalterrestrecosto"] = "InternationalLandFreightCost",
        ["landfreightcost"] = "InternationalLandFreightCost",
        ["bunkercosto"] = "BunkerCost",
        ["bunker"] = "BunkerCost",

        ["origincharges"] = "OriginCharges",
        ["gastosorigen"] = "OriginCharges",
        ["origencharges"] = "OriginCharges",
        ["destinationcharges"] = "DestinationCharges",
        ["gastosdestino"] = "DestinationCharges",
        ["destinocharges"] = "DestinationCharges",

        ["totalcost"] = "TotalCost",
        ["totalcostos"] = "TotalCost",
        ["costototal"] = "TotalCost",
        ["costostotales"] = "TotalCost",
        ["fleteinternacionalventa"] = "InternationalFreightSale",
        ["internationalfreightsale"] = "InternationalFreightSale",
        ["allin"] = "AllInSale",
        ["allinventa"] = "AllInSale",
        ["cargosendestinoventa"] = "DestinationChargesSale",
        ["destinationchargessale"] = "DestinationChargesSale",
        ["carruselventa"] = "CarouselSale",
        ["carouselsale"] = "CarouselSale",
        ["fleteinternoventa"] = "InternalFreightSale",
        ["internalfreightsale"] = "InternalFreightSale",
        ["manejosventa"] = "HandlingSale",
        ["handlingsale"] = "HandlingSale",
        ["totalsale"] = "TotalSale",
        ["venta"] = "TotalSale",
        ["totalventa"] = "TotalSale",
        ["saleamount"] = "TotalSale",
        ["sellingamount"] = "TotalSale",

        ["profit"] = "Profit",
        ["utilidad"] = "Profit",
        ["margin"] = "Margin",
        ["margen"] = "Margin",

        ["space"] = "SpaceComment",
        ["spaces"] = "SpaceComment",
        ["espacios"] = "SpaceComment",
        ["comentarioespacios"] = "SpaceComment",
        ["comentariosdeespacios"] = "SpaceComment",
        ["comentariosespacios"] = "SpaceComment",
        ["remarks"] = "Remarks",
        ["observaciones"] = "Remarks",
        ["comentarios"] = "Remarks",
        ["comment"] = "Remarks",
        ["comments"] = "Remarks",
        ["notes"] = "Remarks",
        ["nota"] = "Remarks",
        ["notas"] = "Remarks",
        ["route"] = "RouteMode",
        ["routemode"] = "RouteMode",
    };
}
