<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDependencyFile>false</GenerateDependencyFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CustomCodeFramework.Core" Version="0.2.0" />
    <PackageReference Include="CustomCodeFramework.Postgres.EntityFramework" Version="0.2.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.8" />
    <PackageReference Include="CustomCodeFramework.Messaging" Version="0.2.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="10.0.10" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Dhole.DataExtraction.Application\Dhole.DataExtraction.Application.csproj" />
    <ProjectReference Include="..\Dhole.DataExtraction.Domain\Dhole.DataExtraction.Domain.csproj" />
    <ProjectReference Include="..\Dhole.DataExtraction.Contracts\Dhole.DataExtraction.Contracts.csproj" />
  </ItemGroup>

</Project>
