// <auto-generated />
using Dhole.DataExtraction.Persistence.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Dhole.DataExtraction.Persistence.Migrations
{
    [DbContext(typeof(ServiceDbContext))]
    [Migration("20260707190000_AddEmailIngestion")]
    partial class AddEmailIngestion
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasDefaultSchema("data_extraction");
#pragma warning restore 612, 618
        }
    }
}
