namespace Dhole.DataExtraction.Contracts.Extraction;

public sealed record ExtractedPricingRowDto(
    Guid Id,
    Guid ExtractionExecutionId,
    Guid SourceDocumentId,
    string? SourceSheetName,
    int? SourceRowNumber,
    string? OriginPort,
    string? PortOfExit,
    string? DestinationPort,
    string? ContainerType,
    string? Carrier,
    string? Agent,
    string? Commodity,
    string? Currency,
    int? FreeDays,
    int? TransitDays,
    DateTime? ValidFrom,
    DateTime? ValidTo,
    decimal? OceanFreight,
    decimal? OriginCharges,
    decimal? DestinationCharges,
    decimal? Surcharges,
    decimal? TotalCost,
    decimal? TotalSale,
    decimal? Profit,
    decimal? Margin,
    string? SpaceComment,
    string? Remarks,
    string Status,
    string? RawJson,
    CatalogReferenceDto? OriginPortReference = null,
    CatalogReferenceDto? PortOfExitReference = null,
    CatalogReferenceDto? DestinationPortReference = null,
    CatalogReferenceDto? ContainerTypeReference = null,
    CatalogReferenceDto? CarrierReference = null,
    CatalogReferenceDto? AgentReference = null,
    CatalogReferenceDto? CurrencyReference = null
);
